#!/bin/sh
set -e

update_dockerd() {
	if [ ! -f /usr/bin/dockerd ]; then
		update-alternatives --install /usr/bin/dockerd dockerd /usr/bin/dockerd-ce 1
	fi
}

case "$1" in
	configure)
		if [ -z "$2" ]; then
			if ! getent group docker > /dev/null; then
				groupadd --system docker
			fi
		fi
		update_dockerd
		;;
	update)
		update_dockerd
		;;
	abort-*)
		# How'd we get here??
		exit 1
		;;
	*)
		;;
esac

#DEBHELPER#
